CREATE PROC FI_SP_PesqBenefPorCpf
	@CPF           VARCHAR (11),
	@ID_CLIENTE	   BIGINT
AS
BEGIN
	SELECT TOP 1 NOME, CPF, ID FROM BENEFICIARIOS 
	WHERE CPF = @CPF AND IDCLIENTE = @ID_CLIENTE
END