CREATE PROC FI_SP_IncOrAltBenef
    @NOME          VARCHAR (50),
	@CPF           VARCHAR (11),
	@ID			BIGINT,
	@ID_CLIENTE    BIGINT
AS
IF(ISNULL(@ID,0) = 0)
	BEGIN
		INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE) VALUES (@NOME, @CPF, @ID_CLIENTE)
		SELECT SCOPE_IDENTITY()
	END
ELSE
	BEGIN
		UPDATE BENEFICIARIOS SET CPF = @CPF, NOME = @NOME WHERE ID = @ID
		SELECT @ID
	END